# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plate_window.ui',
# licensing of 'plate_window.ui' applies.
#
# Created: Mon May 18 18:01:14 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainPlateWindow(object):
    def setupUi(self, MainPlateWindow):
        MainPlateWindow.setObjectName("MainPlateWindow")
        MainPlateWindow.resize(655, 563)
        self.PlateWindow = QtWidgets.QWidget(MainPlateWindow)
        self.PlateWindow.setObjectName("PlateWindow")
        self.gridLayout = QtWidgets.QGridLayout(self.PlateWindow)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.PlateWindow)
        self.tabWidget.setObjectName("tabWidget")
        self.Main = QtWidgets.QWidget()
        self.Main.setObjectName("Main")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Main)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.Main)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.DensityInput = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DensityInput.sizePolicy().hasHeightForWidth())
        self.DensityInput.setSizePolicy(sizePolicy)
        self.DensityInput.setMinimumSize(QtCore.QSize(40, 20))
        self.DensityInput.setMaximumSize(QtCore.QSize(40, 20))
        self.DensityInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.DensityInput.setDecimals(2)
        self.DensityInput.setMinimum(0.01)
        self.DensityInput.setMaximum(5.0)
        self.DensityInput.setSingleStep(0.01)
        self.DensityInput.setProperty("value", 0.5)
        self.DensityInput.setObjectName("DensityInput")
        self.horizontalLayout_4.addWidget(self.DensityInput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.WidthInput = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidthInput.sizePolicy().hasHeightForWidth())
        self.WidthInput.setSizePolicy(sizePolicy)
        self.WidthInput.setMinimumSize(QtCore.QSize(40, 20))
        self.WidthInput.setMaximumSize(QtCore.QSize(40, 20))
        self.WidthInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.WidthInput.setDecimals(2)
        self.WidthInput.setMinimum(0.1)
        self.WidthInput.setMaximum(50.0)
        self.WidthInput.setSingleStep(0.01)
        self.WidthInput.setProperty("value", 5.0)
        self.WidthInput.setObjectName("WidthInput")
        self.horizontalLayout_5.addWidget(self.WidthInput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.HeightInput = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HeightInput.sizePolicy().hasHeightForWidth())
        self.HeightInput.setSizePolicy(sizePolicy)
        self.HeightInput.setMinimumSize(QtCore.QSize(40, 20))
        self.HeightInput.setMaximumSize(QtCore.QSize(40, 20))
        self.HeightInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.HeightInput.setDecimals(2)
        self.HeightInput.setMinimum(0.1)
        self.HeightInput.setMaximum(50.0)
        self.HeightInput.setSingleStep(0.01)
        self.HeightInput.setProperty("value", 5.0)
        self.HeightInput.setObjectName("HeightInput")
        self.horizontalLayout_6.addWidget(self.HeightInput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LoadButton = QtWidgets.QPushButton(self.Main)
        self.LoadButton.setCheckable(False)
        self.LoadButton.setChecked(False)
        self.LoadButton.setObjectName("LoadButton")
        self.verticalLayout.addWidget(self.LoadButton)
        self.SaveButton = QtWidgets.QPushButton(self.Main)
        self.SaveButton.setObjectName("SaveButton")
        self.verticalLayout.addWidget(self.SaveButton)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.Main)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.NameInput = QtWidgets.QLineEdit(self.Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NameInput.sizePolicy().hasHeightForWidth())
        self.NameInput.setSizePolicy(sizePolicy)
        self.NameInput.setMaximumSize(QtCore.QSize(6000, 20))
        self.NameInput.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly)
        self.NameInput.setObjectName("NameInput")
        self.horizontalLayout_14.addWidget(self.NameInput)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.Main)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/menu_pictures/sprites/menu_pictures/picture_of_quantities.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.Main)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.CalculateButton = QtWidgets.QPushButton(self.Main)
        self.CalculateButton.setObjectName("CalculateButton")
        self.horizontalLayout_2.addWidget(self.CalculateButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.label_6 = QtWidgets.QLabel(self.Main)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.frame_2 = QtWidgets.QFrame(self.Main)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.ThicknessInput = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThicknessInput.sizePolicy().hasHeightForWidth())
        self.ThicknessInput.setSizePolicy(sizePolicy)
        self.ThicknessInput.setMinimumSize(QtCore.QSize(40, 20))
        self.ThicknessInput.setMaximumSize(QtCore.QSize(40, 20))
        self.ThicknessInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ThicknessInput.setDecimals(2)
        self.ThicknessInput.setMinimum(0.01)
        self.ThicknessInput.setMaximum(500.0)
        self.ThicknessInput.setSingleStep(0.01)
        self.ThicknessInput.setProperty("value", 25.0)
        self.ThicknessInput.setObjectName("ThicknessInput")
        self.horizontalLayout_8.addWidget(self.ThicknessInput)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.EInput = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EInput.sizePolicy().hasHeightForWidth())
        self.EInput.setSizePolicy(sizePolicy)
        self.EInput.setMinimumSize(QtCore.QSize(40, 20))
        self.EInput.setMaximumSize(QtCore.QSize(40, 20))
        self.EInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.EInput.setDecimals(1)
        self.EInput.setMinimum(1.0)
        self.EInput.setMaximum(400.0)
        self.EInput.setSingleStep(0.1)
        self.EInput.setProperty("value", 30.0)
        self.EInput.setObjectName("EInput")
        self.horizontalLayout_9.addWidget(self.EInput)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.vInput = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vInput.sizePolicy().hasHeightForWidth())
        self.vInput.setSizePolicy(sizePolicy)
        self.vInput.setMinimumSize(QtCore.QSize(40, 20))
        self.vInput.setMaximumSize(QtCore.QSize(40, 20))
        self.vInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vInput.setDecimals(2)
        self.vInput.setMaximum(1.0)
        self.vInput.setSingleStep(0.01)
        self.vInput.setProperty("value", 0.3)
        self.vInput.setObjectName("vInput")
        self.horizontalLayout_10.addWidget(self.vInput)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.TopSupportInput = QtWidgets.QComboBox(self.frame_3)
        self.TopSupportInput.setObjectName("TopSupportInput")
        self.horizontalLayout_7.addWidget(self.TopSupportInput)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.RightSupportInput = QtWidgets.QComboBox(self.frame_3)
        self.RightSupportInput.setObjectName("RightSupportInput")
        self.horizontalLayout_11.addWidget(self.RightSupportInput)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.BottomSupportInput = QtWidgets.QComboBox(self.frame_3)
        self.BottomSupportInput.setObjectName("BottomSupportInput")
        self.horizontalLayout_12.addWidget(self.BottomSupportInput)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.LeftSupportInput = QtWidgets.QComboBox(self.frame_3)
        self.LeftSupportInput.setObjectName("LeftSupportInput")
        self.horizontalLayout_13.addWidget(self.LeftSupportInput)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Main, "")
        self.Loads = QtWidgets.QWidget()
        self.Loads.setObjectName("Loads")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Loads)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.Loads)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/menu_pictures/sprites/menu_pictures/diagram_of_plate_forces.png"))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 2, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.Loads)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_3.addWidget(self.frame_6, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_26 = QtWidgets.QLabel(self.Loads)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_24.addWidget(self.label_26)
        self.QInput = QtWidgets.QDoubleSpinBox(self.Loads)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QInput.sizePolicy().hasHeightForWidth())
        self.QInput.setSizePolicy(sizePolicy)
        self.QInput.setMinimumSize(QtCore.QSize(40, 20))
        self.QInput.setMaximumSize(QtCore.QSize(40, 20))
        self.QInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.QInput.setDecimals(2)
        self.QInput.setMinimum(-10000.0)
        self.QInput.setMaximum(10000.0)
        self.QInput.setSingleStep(0.01)
        self.QInput.setProperty("value", 0.0)
        self.QInput.setObjectName("QInput")
        self.horizontalLayout_24.addWidget(self.QInput)
        self.gridLayout_3.addLayout(self.horizontalLayout_24, 0, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.Loads)
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/menu_pictures/sprites/menu_pictures/positive_sign_direction.png"))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 0, 1, 1, 1)
        self.tabWidget.addTab(self.Loads, "")
        self.Results = QtWidgets.QWidget()
        self.Results.setObjectName("Results")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Results)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = MplWidget(self.Results)
        self.widget.setMinimumSize(QtCore.QSize(0, 400))
        self.widget.setObjectName("widget")
        self.gridLayout_4.addWidget(self.widget, 2, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setHorizontalSpacing(6)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.w_button = QtWidgets.QPushButton(self.Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_button.sizePolicy().hasHeightForWidth())
        self.w_button.setSizePolicy(sizePolicy)
        self.w_button.setObjectName("w_button")
        self.gridLayout_5.addWidget(self.w_button, 0, 0, 1, 1)
        self.Mxx_button = QtWidgets.QPushButton(self.Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mxx_button.sizePolicy().hasHeightForWidth())
        self.Mxx_button.setSizePolicy(sizePolicy)
        self.Mxx_button.setObjectName("Mxx_button")
        self.gridLayout_5.addWidget(self.Mxx_button, 0, 1, 1, 1)
        self.sigma_x_button = QtWidgets.QPushButton(self.Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sigma_x_button.sizePolicy().hasHeightForWidth())
        self.sigma_x_button.setSizePolicy(sizePolicy)
        self.sigma_x_button.setObjectName("sigma_x_button")
        self.gridLayout_5.addWidget(self.sigma_x_button, 0, 2, 1, 1)
        self.Myy_button = QtWidgets.QPushButton(self.Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Myy_button.sizePolicy().hasHeightForWidth())
        self.Myy_button.setSizePolicy(sizePolicy)
        self.Myy_button.setObjectName("Myy_button")
        self.gridLayout_5.addWidget(self.Myy_button, 2, 1, 1, 1)
        self.Mxy_button = QtWidgets.QPushButton(self.Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mxy_button.sizePolicy().hasHeightForWidth())
        self.Mxy_button.setSizePolicy(sizePolicy)
        self.Mxy_button.setObjectName("Mxy_button")
        self.gridLayout_5.addWidget(self.Mxy_button, 3, 1, 1, 1)
        self.sigma_y_button = QtWidgets.QPushButton(self.Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sigma_y_button.sizePolicy().hasHeightForWidth())
        self.sigma_y_button.setSizePolicy(sizePolicy)
        self.sigma_y_button.setObjectName("sigma_y_button")
        self.gridLayout_5.addWidget(self.sigma_y_button, 2, 2, 1, 1)
        self.tau_xy_button = QtWidgets.QPushButton(self.Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tau_xy_button.sizePolicy().hasHeightForWidth())
        self.tau_xy_button.setSizePolicy(sizePolicy)
        self.tau_xy_button.setObjectName("tau_xy_button")
        self.gridLayout_5.addWidget(self.tau_xy_button, 3, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Results, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainPlateWindow.setCentralWidget(self.PlateWindow)
        self.menubar = QtWidgets.QMenuBar(MainPlateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 655, 21))
        self.menubar.setObjectName("menubar")
        self.menuGeometry = QtWidgets.QMenu(self.menubar)
        self.menuGeometry.setObjectName("menuGeometry")
        self.menuLoads = QtWidgets.QMenu(self.menubar)
        self.menuLoads.setObjectName("menuLoads")
        MainPlateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainPlateWindow)
        self.statusbar.setObjectName("statusbar")
        MainPlateWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainPlateWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainPlateWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainPlateWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainPlateWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionClose = QtWidgets.QAction(MainPlateWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout_FIDI = QtWidgets.QAction(MainPlateWindow)
        self.actionAbout_FIDI.setObjectName("actionAbout_FIDI")
        self.menuGeometry.addAction(self.actionNew)
        self.menuGeometry.addAction(self.actionLoad)
        self.menuGeometry.addAction(self.actionSave)
        self.menuGeometry.addAction(self.actionSave_as)
        self.menuGeometry.addAction(self.actionClose)
        self.menuLoads.addAction(self.actionAbout_FIDI)
        self.menubar.addAction(self.menuGeometry.menuAction())
        self.menubar.addAction(self.menuLoads.menuAction())

        self.retranslateUi(MainPlateWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), MainPlateWindow.close)
        QtCore.QObject.connect(self.actionLoad, QtCore.SIGNAL("triggered()"), self.LoadButton.click)
        QtCore.QMetaObject.connectSlotsByName(MainPlateWindow)

    def retranslateUi(self, MainPlateWindow):
        MainPlateWindow.setWindowTitle(QtWidgets.QApplication.translate("MainPlateWindow", "MainWindow", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainPlateWindow", "λ - Mesh density [m] :", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainPlateWindow", "L - Width [m] :", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainPlateWindow", "H - Height [m] :", None, -1))
        self.LoadButton.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Load existing data", None, -1))
        self.SaveButton.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Save data to file", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Name of element :", None, -1))
        self.NameInput.setText(QtWidgets.QApplication.translate("MainPlateWindow", "New_Element", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Calculations :", None, -1))
        self.CalculateButton.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Calculate", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Geometry :", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainPlateWindow", "t - Thickness [cm] :", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainPlateWindow", "E - Modulus of Elasticity [GPa] :", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainPlateWindow", "ν - Poisson\'s Ratio : [-]", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Supports :", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Top edge :", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Right edge :", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainPlateWindow", " Bottom edge :", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Left edge :", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Main), QtWidgets.QApplication.translate("MainPlateWindow", "Main", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainPlateWindow", "uniform normal load [kN/m2] : ", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Loads), QtWidgets.QApplication.translate("MainPlateWindow", "Loads", None, -1))
        self.w_button.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Deflections (w)", None, -1))
        self.Mxx_button.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Moments (Mxx)", None, -1))
        self.sigma_x_button.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Stresses (σx)", None, -1))
        self.Myy_button.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Moments (Myy)", None, -1))
        self.Mxy_button.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Moments (Mxy)", None, -1))
        self.sigma_y_button.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Stesses (σy)", None, -1))
        self.tau_xy_button.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Stresses (τxy)", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Results), QtWidgets.QApplication.translate("MainPlateWindow", "Results", None, -1))
        self.menuGeometry.setTitle(QtWidgets.QApplication.translate("MainPlateWindow", "File", None, -1))
        self.menuLoads.setTitle(QtWidgets.QApplication.translate("MainPlateWindow", "Info", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("MainPlateWindow", "New element", None, -1))
        self.actionLoad.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Load", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Save", None, -1))
        self.actionSave_as.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Save as...", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("MainPlateWindow", "Close", None, -1))
        self.actionAbout_FIDI.setText(QtWidgets.QApplication.translate("MainPlateWindow", "About FIDI", None, -1))

from mplwidget import MplWidget
import Images_rc
